### ISSUE TITLE
Send telegram error

### ISSUE THREAD

**Issue by Andyauk** [Rexshack-RedM/qr-telegram#1]
Read telegram comes up,. but send telegram, this error.
I have all the info added

```
SCRIPT ERROR: @qr-telegram/client/client.lua:68: attempt to concatenate a nil value (local 'telegram')^7
@qr-telegram/client/client.lua^7:68)
@qr-core/client/events.lua^7:190)
```

**Comment by RexShack** [comment]
not able to reproduce this issue you are seeing are you sure you have added the required changes to qr-core\server\player.lua

**Comment by Andyauk** [comment]
> not able to reproduce this issue you are seeing are you sure you have added the required changes to qr-core\server\player.lua

I'll check when home, but had both the same error on my Dev and live server. And 99% sure I have all the changes on the readme and SQL file added.

**Comment by RexShack** [comment]
I am testing on this build : https://github.com/Rexshack-RedM/txAdminRecipe

**Comment by Andyauk** [comment]
> I am testing on this build : https://github.com/Rexshack-RedM/txAdminRecipe

yes i was sure i was. but i got it again and seems to be fine. ill copy it over. thanks.
