### ISSUE TITLE
Error trying to close

### ISSUE THREAD

**Issue by Sina30** [Rexshack-RedM/qr-telegram#2]
[    644438] [b1436_GTAProce]        CrBrowserMain/ Mixed Content: The page at 'https://cfx-nui-qr-telegram/client/html/ui.html' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://qr-telegram/NUIFocusOff'. This request has been blocked; the content must be served over HTTPS. (https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2)

**Comment by RexShack** [comment]
should now be fixed : https://github.com/Rexshack-RedM/qr-telegram/commit/13e73065bc83ee914a9b57316f7c0a58436490a4
